export const init_words = [
	"GTA San Andreas Drifting",
	"jump style",
	"ryan gosling",
	"sus english song lyrics",
	"welding",
	"phonk education",
	"any livestream",
	"iceland",
	"piano two times in a row",
	"chinese soldier propaganda must have flag",
	"hamster costume falling over",
	"patience is key in life",
	"one of our emotes",
	"kobe",
	"Jackass to animals",
	"bald guy falling over",
	"mao zedong",
	"cs2 cool new craft",
	"traktor",
	"cat eating corn",
	"construction",
	"euro truck ,simulator",
	"3 cats in a row",
	"any twitch streamer",
	"irl fishing",
	"jackass to japan",
	"cs2 ace",
	"donald trump",
	"xi yin ping",
	"yesterdays date",
	"cringe	michael ,jackson",
	"giraffe",
	"fire truck",
	"guns twice in a row",
	"joe biden",
	"2 fireworks in a row",
	"thug shaker",
	"breaking bad",
	"cat standing on two feet",
	"chipi chipi",
	"banana cat not crying",
	"basketball",
	"taylor swift",
	"skiing",
	"niko",
	"guitar cable guy",
	"survival video camping",
	"someone eating in car",
	"valorant",
	"tianamen square",
	"cs1.6",
	"cs2 skin over 10k",
	"pubg mobile	",
	"s1mple",
	"beaver",
	"ea sports its in the game",
	"switzerland",
	"liveleak",
	"tyler the creator",
	"the naur guy",
	"crying banana",
	"gmod",
	"two addictions",
];
